# Generated by Django 4.2.3 on 2023-07-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='GoodsList',
        ),
    ]
