# Generated by Django 4.2.3 on 2023-07-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_product_goodslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodslist',
            name='image',
            field=models.ImageField(upload_to='static/products'),
        ),
        migrations.AlterField(
            model_name='goodslist',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
